"""fixed not null

Revision ID: 4016ff8c5c9b
Revises: 9afa1906c401
Create Date: 2025-04-12 17:20:06.315245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4016ff8c5c9b'
down_revision = '9afa1906c401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
