"""removed enrolled column

Revision ID: a0945fb9ed77
Revises: 5a941bdbaafb
Create Date: 2025-04-13 10:06:03.877031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0945fb9ed77'
down_revision = '5a941bdbaafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('enrolled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrolled', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
