"""changed tables

Revision ID: a4886244f32b
Revises: 4016ff8c5c9b
Create Date: 2025-04-12 17:49:07.428870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4886244f32b'
down_revision = '4016ff8c5c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    op.drop_table('department')
    op.drop_table('student')
    op.drop_table('instructor')
    op.drop_table('course')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_courses_department_id_departments', type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_courses_department_id_departments', 'departments', ['department_id'], ['id'])
        batch_op.alter_column('instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.VARCHAR(length=50), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('instructor_id', sa.INTEGER(), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='fk_course_department_id_department'),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], name='fk_course_instructor_id_instructor'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='fk_instructor_department_id_department'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('enrolled', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('head', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('grade', sa.VARCHAR(length=2), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_enrollment_course_id_course'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_enrollment_student_id_student'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
